### ISSUE TITLE
NodeJS `12.13.0` gives an exception for markdown-it but earlier versions works using `vsce`

### ISSUE THREAD

**Issue by gencer** [markdown-it/markdown-it#603]
`vsce` command is for creating and publishing Visual Studio Code extensions. It seems it uses markdown-it somehwere. When I run below command I get an error.

Fails on LTS Version of NodeJS at the moment which is `12.13.0` but it works on earlier versions such as `12.12.0`

Stack trace:

```
internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module './presets/default'
Require stack:
- C:\Users\gence\AppData\Roaming\nvm\v12.13.0\node_modules\vsce\node_modules\markdown-it\lib\index.js
- C:\Users\gence\AppData\Roaming\nvm\v12.13.0\node_modules\vsce\node_modules\markdown-it\index.js
- C:\Users\gence\AppData\Roaming\nvm\v12.13.0\node_modules\vsce\out\package.js
- C:\Users\gence\AppData\Roaming\nvm\v12.13.0\node_modules\vsce\out\main.js
- C:\Users\gence\AppData\Roaming\nvm\v12.13.0\node_modules\vsce\out\vsce
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\gence\AppData\Roaming\nvm\v12.13.0\node_modules\vsce\node_modules\markdown-it\lib\index.js:18:14)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\gence\\AppData\\Roaming\\nvm\\v12.13.0\\node_modules\\vsce\\node_modules\\markdown-it\\lib\\index.js',
    'C:\\Users\\gence\\AppData\\Roaming\\nvm\\v12.13.0\\node_modules\\vsce\\node_modules\\markdown-it\\index.js',
    'C:\\Users\\gence\\AppData\\Roaming\\nvm\\v12.13.0\\node_modules\\vsce\\out\\package.js',
    'C:\\Users\\gence\\AppData\\Roaming\\nvm\\v12.13.0\\node_modules\\vsce\\out\\main.js',
    'C:\\Users\\gence\\AppData\\Roaming\\nvm\\v12.13.0\\node_modules\\vsce\\out\\vsce'
  ]
}

```

See: https://github.com/microsoft/vscode-vsce/issues/397

This could be an issue on this side, so, I open an another issue here.

**Comment by puzrin** [comment]
https://travis-ci.org/markdown-it/markdown-it/jobs/583376969 this package is tested on CI with latest node version, and does not seems to have issue with node 12.

Can not respond for third-party browserifiers/loaders. Tend to close this as not this  package bug.

**Comment by gencer** [comment]
@puzrin Fair enough, however, are you sure about Travis CI runs latest version? I see its `12.10.0`. It works on me on that version too. I'm talking about `12.13.0`

![image](https://user-images.githubusercontent.com/1711576/67435175-42059c00-f5f4-11e9-8f60-b57de1a0f7c8.png)


Deeply sorry if I misunderstand this.

**Comment by puzrin** [comment]
It works with 12.13.0 too. You can use `nvm` and try any node version you wish, `npm test`.

**Comment by gencer** [comment]
Very well, this issue may be closed then.

Thanks for the heads up.
